CREATE DATABASE IF NOT EXISTS smart_warehouse CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE smart_warehouse;

CREATE TABLE IF NOT EXISTS orders (id BIGINT PRIMARY KEY AUTO_INCREMENT, external_id VARCHAR(64) NOT NULL UNIQUE, status VARCHAR(32) NOT NULL, risk VARCHAR(16) NOT NULL, requester VARCHAR(160) NOT NULL, total DECIMAL(14,2), requested_at DATETIME NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS stock_items (id BIGINT PRIMARY KEY AUTO_INCREMENT, sku VARCHAR(64) NOT NULL UNIQUE, description VARCHAR(255) NOT NULL, quantity DECIMAL(14,3) NOT NULL DEFAULT 0, minimum_quantity DECIMAL(14,3) NOT NULL DEFAULT 0, location VARCHAR(64), updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS documents (id BIGINT PRIMARY KEY AUTO_INCREMENT, document_type VARCHAR(32) NOT NULL, storage_key VARCHAR(512) NOT NULL, extraction_status VARCHAR(32) NOT NULL, confidence DECIMAL(5,4), extracted_json JSON, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS required_procedures (id BIGINT PRIMARY KEY AUTO_INCREMENT, code VARCHAR(64) NOT NULL UNIQUE, name VARCHAR(255) NOT NULL, active BOOLEAN NOT NULL DEFAULT TRUE);
CREATE TABLE IF NOT EXISTS audit_events (id BIGINT PRIMARY KEY AUTO_INCREMENT, event_type VARCHAR(64) NOT NULL, severity VARCHAR(16) NOT NULL, aggregate_type VARCHAR(64), aggregate_id VARCHAR(64), payload JSON NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
