"""Puertos de salida para desacoplar casos de uso de MySQL, S3, ERP o WMS."""
from typing import Iterable, Protocol, Sequence


class WarehouseRepository(Protocol):
    def count(self, table: str) -> int: ...

    def list_orders(self, status: str | None = None) -> Sequence[dict]: ...

    def get_order(self, external_id: str) -> dict | None: ...

    def transition_order_status(self, external_id: str, to_status: str, reason: str | None = None) -> dict: ...

    def list_order_status_history(self, external_id: str) -> Sequence[dict]: ...

    def list_stock(self) -> Sequence[dict]: ...

    def list_stock_movements(self, sku: str | None = None, limit: int = 100) -> Sequence[dict]: ...

    def create_stock_movement(self, payload: dict) -> dict: ...

    def list_suppliers(self) -> Sequence[dict]: ...

    def list_invoices(self) -> Sequence[dict]: ...

    def reconcile_invoice(self, invoice_number: str) -> dict: ...

    def accounting_export_rows(self) -> Sequence[dict]: ...

    def mark_invoice_exported(self, invoice_number: str, export_format: str, target_system: str) -> dict: ...

    def list_procedures(self, external_id: str | None = None) -> Sequence[dict]: ...

    def save_invoice_document(self, filename: str, mime_type: str, content: bytes, extracted: dict) -> dict: ...

    def save_procedure_document(self, external_id: str, procedure_code: str, filename: str, mime_type: str, content: bytes) -> dict: ...

    def list_receipts(self) -> Sequence[dict]: ...

    def create_receipt(self, payload: dict) -> dict: ...

    def list_events(self, limit: int = 50, severity: str | None = None, event_type: str | None = None, aggregate_type: str | None = None) -> Sequence[dict]: ...

    def get_event(self, event_id: int) -> dict | None: ...

    def list_alerts(self, limit: int = 50, severity: str | None = None, event_type: str | None = None, status: str = "unread") -> Sequence[dict]: ...

    def mark_alert_read(self, alert_id: int) -> dict: ...

    def mark_all_alerts_read(self) -> int: ...

    def list_alert_rules(self) -> Sequence[dict]: ...

    def create_alert_rule(self, payload: dict) -> dict: ...

    def update_alert_rule(self, rule_id: int, payload: dict) -> dict: ...

    def list_decisions(self, external_id: str) -> Sequence[dict]: ...

    def save_validation(self, external_id: str, decision: dict) -> None: ...

    def create_order(self, payload: dict) -> dict: ...

    def import_orders(self, rows: list[dict]) -> dict: ...

class OrderRepository(Protocol):
    def list_pending(self) -> Iterable[dict]: ...

class DocumentRepository(Protocol):
    def save_extracted_invoice(self, invoice: dict) -> str: ...

class DecisionPublisher(Protocol):
    def publish(self, event: dict) -> None: ...

class AccountingExporter(Protocol):
    def export_invoice(self, invoice: dict) -> dict: ...
