import { useEffect, useState } from 'react'
import { NavLink, Route, Routes, useLocation, useParams } from 'react-router-dom'
import { kpis, orders, stock, suppliers, events, invoices } from './domain/mockData'
import { warehouseService } from './application/useWarehouse'

const nav = [
  { to: '/', label: 'Resumen', icon: 'bi-grid-1x2-fill', end: true },
  { to: '/pedidos', label: 'Pedidos y compras', icon: 'bi-cart3', count: '24' },
  { to: '/stock', label: 'Stock', icon: 'bi-box-seam' },
  { to: '/recepcion', label: 'Recepción y almacén', icon: 'bi-arrow-down-square' },
  { to: '/proveedores', label: 'Proveedores', icon: 'bi-building' },
  { to: '/documentos', label: 'Documentos y facturas', icon: 'bi-file-earmark-text', count: '3' },
  { to: '/eventos', label: 'Eventos y alertas', icon: 'bi-activity', count: '7' },
]

function App() {
  const [copilot, setCopilot] = useState(false)
  const [data, setData] = useState(null)
  useEffect(() => { warehouseService.loadDashboard().then(setData) }, [])
  return <div className="app-shell">
    <main className="main-area">
      <Header onCopilot={() => setCopilot(true)} />
      <div className="page-content container"><Routes>
        <Route path="/" element={<Dashboard />} />
        <Route path="/pedidos" element={<Orders />} />
        <Route path="/pedidos/:id" element={<OrderDetail />} />
        <Route path="/stock" element={<Stock />} />
        <Route path="/recepcion" element={<Receiving />} />
        <Route path="/proveedores" element={<Suppliers />} />
        <Route path="/documentos" element={<Documents />} />
        <Route path="/eventos" element={<Events />} />
      </Routes></div>
    </main>
    {copilot && <Copilot onClose={() => setCopilot(false)} />}
  </div>
}

function Header({ onCopilot }) { const location = useLocation(); const title = nav.find(x => x.to === location.pathname)?.label || 'Detalle de operación'; const moreActive = nav.slice(4).some(item => location.pathname.startsWith(item.to)); return <header className={`topbar ${location.pathname === '/' ? 'dashboard-topbar' : ''}`}><div className="container"><div className="row align-items-center gy-3"><div className="col-12 col-xl-3"><NavLink to="/" className="top-brand"><span className="brand-mark"><i className="bi bi-boxes" /></span><span><strong>smart<span>warehouse</span></strong><small>CONTROL CENTER</small></span></NavLink></div><div className="col-12 col-xl-7"><nav className="top-menu nav nav-pills">{nav.slice(0, 4).map(item => <NavLink key={item.to} to={item.to} end={item.end} className={({ isActive }) => isActive ? 'nav-link active' : 'nav-link'}><i className={`bi ${item.icon}`} /><span>{item.label}</span>{item.count && <em>{item.count}</em>}</NavLink>)}<details className={`top-dropdown ${moreActive ? 'active' : ''}`}><summary className="nav-link"><i className="bi bi-three-dots" /><span>Más</span><i className="bi bi-chevron-down dropdown-chevron" /></summary><div className="dropdown-menu show">{nav.slice(4).map(item => <NavLink key={item.to} to={item.to} className={({ isActive }) => isActive ? 'dropdown-item active' : 'dropdown-item'}><i className={`bi ${item.icon}`} /><span>{item.label}</span>{item.count && <em>{item.count}</em>}</NavLink>)}</div></details></nav></div><div className="col-12 col-xl-2"><div className="top-actions justify-content-xl-end"><button className="icon-btn" title="Buscar"><i className="bi bi-search" /></button><button className="icon-btn notification" title="Notificaciones"><i className="bi bi-bell" /><b>3</b></button><button className="copilot-btn" onClick={onCopilot}><i className="bi bi-stars" /> Copilot</button></div></div></div>{location.pathname !== '/' && <div className="row"><div className="col-12"><h1>{title}</h1></div></div>}</div></header> }

const PageTitle = ({ eyebrow, title, children }) => <div className="page-title"><div><div className="eyebrow">{eyebrow}</div><h2>{title}</h2></div><div className="page-actions">{children}</div></div>
const Button = ({ children, primary = false }) => <button className={primary ? 'btn-main' : 'btn-ghost'}>{children}</button>
const Risk = ({ risk }) => <span className={`risk risk-${risk}`}><i className="bi bi-circle-fill" /></span>
const Status = ({ children, tone = 'neutral' }) => <span className={`status status-${tone}`}>{children}</span>

function Dashboard() { return <><PageTitle eyebrow="CENTRO DE CONTROL · 25 SEP 2025" title="Vista general"><Button><i className="bi bi-calendar3" /> Hoy, 25 sep 2025</Button><Button primary><i className="bi bi-plus-lg" /> Nuevo pedido</Button></PageTitle>
  <section className="kpi-grid">{kpis.map(k => <div className="kpi-card" key={k.label}><div className={`kpi-icon ${k.tone}`}><i className={`bi ${k.icon}`} /></div><div><span>{k.label}</span><strong>{k.value}</strong><small className={k.tone === 'danger' ? 'text-danger' : 'text-success'}><i className={`bi ${k.tone === 'danger' ? 'bi-exclamation-circle' : 'bi-arrow-up-right'}`} /> {k.change}</small></div></div>)}</section>
  <div className="dashboard-grid"><section className="panel panel-orders"><PanelHead title="Cola de validación" subtitle="Pedidos que requieren decisión" action="Ver todos" />{orders.slice(0, 4).map(order => <OrderRow order={order} key={order.id} />)}</section><section className="panel health-panel"><PanelHead title="Salud operativa" subtitle="Estado del almacén en tiempo real" /><div className="health-score"><div className="score-ring"><strong>94</strong><span>/100</span></div><div><strong>Operación saludable</strong><p>Sin bloqueos críticos en el flujo</p></div></div><div className="health-bars"><Metric label="Pedidos a tiempo" value="96,8%" width="96%" tone="success" /><Metric label="Precisión de stock" value="99,1%" width="99%" tone="info" /><Metric label="Documentación completa" value="82,4%" width="82%" tone="warning" /></div></section></div>
  <div className="dashboard-grid lower"><section className="panel"><PanelHead title="Actividad reciente" subtitle="Eventos del sistema y del motor IA" action="Ver registro" /> <div className="event-list">{events.slice(0, 4).map(e => <EventRow event={e} key={e.time} />)}</div></section><section className="panel insight-panel"><div className="insight-head"><div className="ai-spark"><i className="bi bi-stars" /></div><div><div className="eyebrow">INSIGHT DEL COPILOT</div><h3>Hay una decisión pendiente</h3></div></div><p>El pedido <strong>PED-2025-00482</strong> tiene un volumen 10× superior a la media. Hay stock parcial disponible y la demanda prevista no lo justifica.</p><button className="text-link">Revisar recomendación <i className="bi bi-arrow-right" /></button></section></div>
</> }

function PanelHead({ title, subtitle, action }) { return <div className="panel-head"><div><h3>{title}</h3><p>{subtitle}</p></div>{action && <button className="text-link">{action} <i className="bi bi-arrow-up-right" /></button>}</div> }
function OrderRow({ order }) { return <div className="order-row"><Risk risk={order.risk} /><div className="order-main"><strong>{order.id}</strong><span>{order.product}</span></div><div className="order-requester">{order.requester}<small>{order.qty} uds. · {order.total}</small></div><Status tone={order.risk === 'green' ? 'success' : order.risk === 'red' ? 'danger' : 'warning'}>{order.status}</Status><i className="bi bi-chevron-right row-chevron" /></div> }
function Metric({ label, value, width, tone }) { return <div className="metric"><div><span>{label}</span><strong>{value}</strong></div><div className="progress"><div className={`progress-bar bg-${tone}`} style={{ width }} /></div></div> }
function EventRow({ event }) { return <div className="event-row"><span className={`event-dot ${event.tone}`} /><div><div><strong>{event.text}</strong><small>{event.time} · {event.type}</small></div><p>{event.detail}</p></div></div> }

function Orders() { return <><PageTitle eyebrow="OPERACIONES / COMPRAS" title="Pedidos y validación"><Button><i className="bi bi-download" /> Exportar</Button><Button primary><i className="bi bi-plus-lg" /> Crear pedido</Button></PageTitle><div className="filter-bar"><div className="search-field"><i className="bi bi-search" /><input placeholder="Buscar por pedido, producto o empleado..." /></div><button>Todos los estados <i className="bi bi-chevron-down" /></button><button>Últimos 30 días <i className="bi bi-chevron-down" /></button><span className="filter-spacer" /><span className="view-toggle active"><i className="bi bi-list" /></span><span className="view-toggle"><i className="bi bi-grid" /></span></div><section className="panel table-panel"><div className="table-meta"><span><strong>24</strong> pedidos en cola</span><span className="legend"><Risk risk="green" /> Aprobado <Risk risk="yellow" /> Revisar <Risk risk="red" /> Bloqueado</span></div><table><thead><tr><th>RIESGO</th><th>PEDIDO / PRODUCTO</th><th>SOLICITANTE</th><th>IMPORTE</th><th>ESTADO</th><th>FECHA</th><th /></tr></thead><tbody>{orders.map(o => <tr key={o.id}><td><Risk risk={o.risk} /></td><td><NavLink className="order-link" to={`/pedidos/${o.id}`}><strong>{o.id}</strong><small>{o.product}</small></NavLink></td><td>{o.requester}<small>{o.area}</small></td><td><strong>{o.total}</strong><small>{o.qty} unidades</small></td><td><Status tone={o.risk === 'green' ? 'success' : o.risk === 'red' ? 'danger' : 'warning'}>{o.status}</Status><small className="reason">{o.reason}</small></td><td className="muted">{o.date}</td><td><button className="more"><i className="bi bi-three-dots" /></button></td></tr>)}</tbody></table></section></> }

function OrderDetail() { const { id } = useParams(); const order = orders.find(item => item.id === id) || orders[0]; return <><div className="detail-back"><NavLink to="/pedidos"><i className="bi bi-arrow-left" /> Volver a pedidos</NavLink></div><PageTitle eyebrow={`PEDIDO / ${order.id}`} title="Detalle y validación"><Button><i className="bi bi-download" /> Exportar ficha</Button><Button primary><i className="bi bi-check2" /> Aprobar manualmente</Button></PageTitle><div className="detail-grid"><section className="panel"><div className="detail-order-head"><div className="risk risk-large risk-red"><i className="bi bi-circle-fill" /></div><div><h3>{order.product}</h3><span>{order.id} · creado por {order.requester} · {order.date}</span></div><Status tone="danger">Revisión humana</Status></div><div className="detail-metrics"><div><span>Cantidad solicitada</span><strong>{order.qty} uds.</strong></div><div><span>Importe total</span><strong>{order.total}</strong></div><div><span>Proveedor</span><strong>Roca Sanitario, S.A.</strong></div><div><span>Entrega estimada</span><strong>28 sep 2025</strong></div></div><div className="decision-note"><i className="bi bi-exclamation-triangle" /><div><strong>La IA recomienda revisar antes de aprobar</strong><p>Se ha detenido el envío automático para proteger el capital inmovilizado y evitar una recepción no planificada.</p></div></div></section><section className="panel validation-panel"><PanelHead title="Validación inteligente" subtitle="Reglas deterministas · 09:42:18" /><ValidationRow icon="bi-box-seam" title="Stock actual" value="86 uds. disponibles" status="warning" detail="Hay stock parcial, pero no cubre el pedido completo" /><ValidationRow icon="bi-graph-up" title="Histórico de pedidos" value="Media: 24 uds." status="danger" detail="El volumen solicitado es 10,4× superior a la media" /><ValidationRow icon="bi-bar-chart-line" title="Demanda prevista" value="18 uds. / 30 días" status="danger" detail="La demanda no justifica el volumen solicitado" /><ValidationRow icon="bi-file-earmark-check" title="Procedimientos" value="Completos" status="success" detail="Documentación obligatoria encontrada" /></section></div><section className="panel recommendation-panel"><div className="ai-spark"><i className="bi bi-stars" /></div><div><div className="eyebrow">SUGERENCIA EXPLICABLE DEL COPILOT</div><h3>Solicitar confirmación de 25 unidades</h3><p>Una cantidad de 25 uds. cubre la demanda prevista y mantiene un margen de seguridad razonable. También puedes dividir el pedido en dos entregas.</p></div><Button primary>Aplicar sugerencia</Button></section></> }
function ValidationRow({ icon, title, value, status, detail }) { return <div className="validation-row"><div className={`validation-icon ${status}`}><i className={`bi ${icon}`} /></div><div><strong>{title}</strong><span>{detail}</span></div><div className="validation-result"><Status tone={status}>{value}</Status><Risk risk={status === 'success' ? 'green' : status === 'danger' ? 'red' : 'yellow'} /></div></div> }

function Stock() { return <><PageTitle eyebrow="OPERACIONES / INVENTARIO" title="Stock y disponibilidad"><Button><i className="bi bi-upload" /> Importar plantilla</Button><Button primary><i className="bi bi-box-arrow-in-down" /> Registrar entrada</Button></PageTitle><div className="stock-summary"><div><span>Referencias activas</span><strong>8.492</strong><small>+124 este mes</small></div><div><span>Valor de inventario</span><strong>1,24 M€</strong><small>+3,2% vs. mes anterior</small></div><div><span>Por debajo de mínimo</span><strong className="danger-number">143</strong><small>12 críticas</small></div><div><span>Exactitud inventario</span><strong>99,1%</strong><small>Objetivo: 98%</small></div></div><section className="panel table-panel"><div className="table-meta"><span><strong>Inventario principal</strong> · 6 referencias destacadas</span><div className="search-field compact"><i className="bi bi-search" /><input placeholder="Filtrar SKU..." /></div></div><table><thead><tr><th>SKU</th><th>PRODUCTO</th><th>CATEGORÍA</th><th>STOCK</th><th>DEMANDA</th><th>UBICACIÓN</th><th>ESTADO</th></tr></thead><tbody>{stock.map(s => <tr key={s.sku}><td><strong className="sku">{s.sku}</strong></td><td><strong>{s.product}</strong><small>Actualizado hace 12 min</small></td><td>{s.category}</td><td><strong>{s.stock.toLocaleString('es-ES')}</strong><small>Mín. {s.min}</small></td><td><span className={`demand demand-${s.demand.toLowerCase()}`}><i className="bi bi-graph-up" /> {s.demand}</span></td><td className="muted"><i className="bi bi-geo-alt" /> {s.location}</td><td><Status tone={s.status === 'Óptimo' ? 'success' : 'warning'}>{s.status}</Status></td></tr>)}</tbody></table></section></> }

function Receiving() { return <><PageTitle eyebrow="OPERACIONES / LOGÍSTICA" title="Recepción y almacén"><Button><i className="bi bi-printer" /> Imprimir etiquetas</Button><Button primary><i className="bi bi-box-arrow-in-down" /> Nueva recepción</Button></PageTitle><div className="receiving-grid"><section className="panel"><PanelHead title="Muelles de recepción" subtitle="Estado actual · 25 septiembre" /><div className="dock-grid"><Dock name="Muelle 01" supplier="Saltoki Suministros" eta="09:30" status="Descargando" tone="success" /><Dock name="Muelle 02" supplier="General Cable" eta="10:15" status="En camino" tone="info" /><Dock name="Muelle 03" supplier="Roca Sanitario" eta="11:00" status="Programado" tone="warning" /><Dock name="Muelle 04" supplier="Libre" eta="—" status="Disponible" tone="neutral" /></div></section><section className="panel capacity"><PanelHead title="Capacidad del almacén" subtitle="Ocupación por zona" /><div className="warehouse-map"><div className="zone zone-a">A <small>78%</small></div><div className="zone zone-b">B <small>64%</small></div><div className="zone zone-c">C <small>91%</small></div><div className="zone zone-d">D <small>42%</small></div></div><div className="map-legend"><span><i className="legend-dot green" /> Disponible</span><span><i className="legend-dot yellow" /> Atención</span><span><i className="legend-dot red" /> Saturada</span></div></section></div><section className="panel timeline-panel"><PanelHead title="Próximas recepciones" subtitle="Pedidos confirmados con proveedor" action="Ver agenda" />{['PED-2025-00481 · Tubo multicapa PEX 16 mm','PED-2025-00476 · Cable RZ1-K 3G2.5','PED-2025-00470 · Panel LED 60×60 40W'].map((x,i) => <div className="receiving-row" key={x}><div className="time-block"><strong>{['09:30','10:15','11:00'][i]}</strong><small>HOY</small></div><div><strong>{x.split(' · ')[0]}</strong><span>{x.split(' · ')[1]}</span></div><Status tone={i === 0 ? 'success' : 'info'}>{['Descargando','En camino','Programado'][i]}</Status><span className="muted">{['Muelle 01','Muelle 02','Muelle 03'][i]}</span></div>)}</section></> }
function Dock({ name, supplier, eta, status, tone }) { return <div className="dock-card"><div className="dock-number"><i className="bi bi-truck" /></div><div><strong>{name}</strong><span>{supplier}</span><small>ETA {eta}</small></div><Status tone={tone}>{status}</Status></div> }

function Suppliers() { return <><PageTitle eyebrow="MAESTROS / PARTNERS" title="Proveedores"><Button><i className="bi bi-download" /> Exportar</Button><Button primary><i className="bi bi-plus-lg" /> Añadir proveedor</Button></PageTitle><div className="supplier-cards"><div><i className="bi bi-building" /><strong>128</strong><span>Proveedores activos</span></div><div><i className="bi bi-link-45deg" /><strong>76</strong><span>Conectados por API</span></div><div><i className="bi bi-star" /><strong>4,6 / 5</strong><span>Valoración media</span></div></div><section className="panel table-panel"><div className="table-meta"><span><strong>Red de proveedores</strong></span><div className="search-field compact"><i className="bi bi-search" /><input placeholder="Buscar proveedor..." /></div></div><table><thead><tr><th>PROVEEDOR</th><th>CATEGORÍA</th><th>PEDIDOS YTD</th><th>VALORACIÓN</th><th>PLAZO MEDIO</th><th>ESTADO</th></tr></thead><tbody>{suppliers.map(s => <tr key={s.name}><td><div className="supplier-name"><div className="supplier-avatar">{s.name.slice(0,2).toUpperCase()}</div><strong>{s.name}</strong></div></td><td>{s.category}</td><td>{s.orders}</td><td><span className="rating"><i className="bi bi-star-fill" /> {s.rating}</span></td><td>{s.lead}</td><td><Status tone={s.status === 'Conectado' ? 'success' : 'warning'}>{s.status}</Status></td></tr>)}</tbody></table></section></> }

function Documents() { return <><PageTitle eyebrow="CONTROL DOCUMENTAL" title="Facturas y documentos"><Button><i className="bi bi-file-earmark-arrow-up" /> Subir factura</Button><Button primary><i className="bi bi-file-earmark-spreadsheet" /> Plantillas de importación</Button></PageTitle><div className="document-banner"><div className="ai-spark"><i className="bi bi-stars" /></div><div><strong>Interpretación inteligente activa</strong><p>El sistema extrae proveedor, líneas, impuestos y totales de PDFs digitales y documentos escaneados.</p></div><span className="confidence">98,7% confianza media</span></div><section className="panel table-panel"><div className="table-meta"><span><strong>Facturas recibidas</strong> · 3 pendientes de acción</span><button className="text-link">Exportar a contabilidad <i className="bi bi-box-arrow-up-right" /></button></div><table><thead><tr><th>DOCUMENTO</th><th>PROVEEDOR</th><th>FECHA</th><th>IMPORTE</th><th>CONFIANZA IA</th><th>ESTADO</th></tr></thead><tbody>{invoices.map(x => <tr key={x.id}><td><div className="doc-name"><i className="bi bi-file-earmark-pdf" /><div><strong>{x.id}</strong><small>{x.type}</small></div></div></td><td>{x.supplier}</td><td>{x.date}</td><td><strong>{x.amount}</strong></td><td><span className="confidence-text"><i className="bi bi-check-circle-fill" /> {x.confidence}</span></td><td><Status tone={x.status === 'Conciliada' || x.status === 'Exportable' ? 'success' : 'warning'}>{x.status}</Status></td></tr>)}</tbody></table></section><section className="panel procedure-panel"><div className="procedure-icon"><i className="bi bi-shield-check" /></div><div><h3>Documentación obligatoria del proceso</h3><p>Hay <strong>2 procedimientos sin adjuntar</strong> en operaciones recientes. El motor IA bloqueará automáticamente pedidos de riesgo hasta que se completen.</p></div><button className="text-link">Gestionar procedimientos <i className="bi bi-arrow-right" /></button></section></> }

function Events() { return <><PageTitle eyebrow="OBSERVABILIDAD / AUDITORÍA" title="Eventos y alertas"><Button><i className="bi bi-download" /> Descargar registro</Button><Button primary><i className="bi bi-sliders" /> Configurar alertas</Button></PageTitle><div className="alert-cards"><div className="alert-critical"><i className="bi bi-exclamation-octagon" /><div><strong>3</strong><span>Alertas críticas</span></div><button>Revisar <i className="bi bi-arrow-right" /></button></div><div className="alert-warning"><i className="bi bi-exclamation-triangle" /><div><strong>4</strong><span>Requieren atención</span></div><button>Revisar <i className="bi bi-arrow-right" /></button></div><div className="alert-ok"><i className="bi bi-check-circle" /><div><strong>1.248</strong><span>Eventos procesados hoy</span></div></div></div><section className="panel event-log"><div className="table-meta"><span><strong>Registro de actividad</strong></span><div className="log-filters"><span className="active">Todos</span><span>IA</span><span>Pedidos</span><span>Documentos</span></div></div>{events.concat(events.slice(0,2)).map((e,i) => <EventRow event={{...e,time: i > 4 ? '08:5'+i+':12' : e.time}} key={i} />)}</section></> }

function Copilot({ onClose }) { const [query, setQuery] = useState(''); const [sent, setSent] = useState(false); return <div className="copilot-overlay" onClick={onClose}><aside className="copilot-panel" onClick={e => e.stopPropagation()}><div className="copilot-header"><div className="copilot-title"><div className="ai-spark"><i className="bi bi-stars" /></div><div><strong>Warehouse Copilot</strong><span>Contexto operativo · actualizado ahora</span></div></div><button className="icon-btn" onClick={onClose}><i className="bi bi-x-lg" /></button></div><div className="copilot-body"><div className="copilot-welcome"><div className="ai-spark large"><i className="bi bi-stars" /></div><h3>¿En qué puedo ayudarte?</h3><p>Consulto pedidos, stock, proveedores, documentos y eventos de tu operación.</p></div><div className="suggestions"><button onClick={() => setQuery('¿Qué pedidos necesitan revisión humana?')}>Pedidos para revisar <i className="bi bi-arrow-up-right" /></button><button onClick={() => setQuery('¿Qué referencias están por debajo del mínimo?')}>Stock crítico <i className="bi bi-arrow-up-right" /></button><button onClick={() => setQuery('Resume las alertas de hoy')}>Alertas de hoy <i className="bi bi-arrow-up-right" /></button></div>{sent && <div className="chat-answer"><small>WAREHOUSE COPILOT · AHORA</small><p>He encontrado <strong>3 pedidos</strong> que requieren revisión humana. El más urgente es <strong>PED-2025-00482</strong>: 250 grifos, volumen 10× superior a la media histórica.</p><button className="text-link">Abrir pedido <i className="bi bi-arrow-right" /></button></div>}</div><form className="copilot-input" onSubmit={e => { e.preventDefault(); setSent(true); }}><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Pregunta sobre tu operación..." /><button><i className="bi bi-arrow-up" /></button></form></aside></div> }

export default App
